VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAHOVX34KDN2VEXVBTVKKBN57MDZSBCQFFSN7K6AXWVJDL6AZNM3MTZG",
"GDGGIT3AXOQ25CCRECFJZQRHAXBSOBRTQ4C3XFCDPO3Q6MLM4M23S7TE"
]

[DOCUMENTATION]
ORG_NAME="Sword & Shield"
ORG_LOGO="https://ibb.co/LhSr58V"
ORG_DESCRIPTION="The Sword and Shield token was created by the Era Touch development team. We have launched our own direction in the crypto industry to promote historical reports, etc . We support and sponsor all archaeological discoveries . We also sponsor the restoration of museums and galleries, create auctions to support the sick, orphans and people who have fallen into the most difficult life situations, by buying our coins, you will not only earn money, but also leave a mark on this planet"
ORG_PHYSICAL_ADDRESS="3770 S University Center Dr, Las Vegas, NV 89119"
ORG_PHONE_NUMBER="+1 702-734-6788"
ORG_KEYBASE="Magofox"
ORG_OFFICIAL_EMAIL="eratouch@gmail.com"

[[CURRENCIES]]
code="Sword&Shield"
issuer="GAHOVX34KDN2VEXVBTVKKBN57MDZSBCQFFSN7K6AXWVJDL6AZNM3MTZG"
display_decimals=0
is_asset_anchored=false
name="sword&shield"
desc="The Sword and Shield token was created by the Era Touch development team. We have launched our own direction in the crypto industry to promote historical reports, etc . We support and sponsor all archaeological discoveries . We also sponsor the restoration of museums and galleries, create auctions to support the sick, orphans and people who have fallen into the most difficult life situations, by buying our coins, you will not only earn money, but also leave a mark on this planet"
conditions="There will be 1000000000 now and forever"
image="https://ibb.co/LhSr58V"
# sword&shield (SWORD&Shield) Token was issued using the open and inclusive Stellar blockchain network.
# Home Domain: eratouch.com
# Sword&Shield Token
